### PR TITLE
Preferences screen as a fragment

### PR DESCRIPTION
**Pull request by fynngodau**
Hello everyone. We had been were looking for a good Moodle client and since yours is hardcoded to use your university, we made [a fork of your app](https://codeberg.org/fynngodau/moodleDirect) (name subject to change), primarily to allow users to configure a moodle instance of their choice.

While doing that I also made some commits that I thought you might profit from as well, so I decided to open this pull request.

In the fork, I removed the `SettingsActivity` and instead used the `androidx.preference` library. This has a number of benefits: preferences can easily be added using an XML file, which can automatically be stored in the shared preferences (for checkboxes, lists, text inputs…). This allows allows new preferences to be added without much effort. It is also now a fragment instead of an activity, so the drawer is still accessible on this page. Dark mode is immediately applied, however, still.

Unfortunately, I had to add the notifications settings partly manually again because it is stored in a different preference file than the default one.

Furthermore, I replaced the bell png icons with an xml vector drawable that changes color based on theme in order to place it on the preferences screen.

Additionally, I modified the `UserAccount` class to look more clean and not create a new instance of `SharedPreferences` every call.

Due to lack of login to your university's moodle, I couldn't test whether it works, but pretty much the same commits in our fork work for us.

### CODE REVIEW

**Comment by fynngodau** [comment]
A force push to your dev branch has caused commits that were removed from it to appear again in this as well as my other pull request.

There is currently the issue that when switching to the preferences fragment, switching to another fragment and switching back to the preferences fragment using the back button, the other fragment's entry in the sidebar menu will still be highlighted. I don't know why this doesn't happen with the other entries, I couldn't find corresponding code.

**Comment by abhijeetviswa** [comment]
Hey,

Yea, missed out a couple of commits during the last release of the app. I was in a hurry and stupid of me. I didn't realize this until the next time I started working on the issues. Stupid of me. 

As for your PR, thank you for your contributions. However, we aren't really interested in removing our college specific code and instead adding in a separate screen. The reason being, it'll upend the current UX that our users had so far. 

However, if you are interested, we could create a separate upstream repo that both of us can contribute to together, removing all the college specific things and leaving it as generic as possible. Any things specific to your college our ours can be added after rebasing the upstream change. I believe, this synergy would will help improve the project as a whole. 

Regards.

**Comment by fynngodau** [comment]
Hello,

we believe there has been some confusion about this pull request. In our fork, we removed code specific to your university, but in this pull request, there are only patches that do not touch the login procedure. This means I took (only) those patches that (in my opinion, as described above) improve the settings screen and applied them to your branch.

I had been planning to do the same for other things we are adding. For example, today we have been working on support for the choice module. I have been planning to rebase the changes that add this functionality onto your branch once we are done with the feature in order to open a new pull request.

In theory it would be possible to build both variants of the app from the same source repository by using build flavors. However this is a little tricky, and we would prefer not to have code associated with Google login for feedback forms or the like in the repository we compile the app from.

On the other hand it would in total be the same as using a shared upstream, except that it would likely be less work as no merging would have to be done.

**Comment by abhijeetviswa** [comment]
I finally got time to reviewing this patch.

Thanks for the PR. I've rebased to the `development`. Further, I've also made a couple of changes to the visual aspect of the PR so that the changes are less obvious to our users. These are:

1.  Changed the title of the fragment.
2. Changed the font of the preference text.
3. Changed the `CheckboxPreference` to a `SwitchPreference`.

I'll be merging these in soon. Once again, Thanks for the PR.

Regards.

PS: I'll review your other PRs ASAP.

**Pull request merged**
