### PR TITLE
Replace "filter" with "search" in my courses search bar

### PR DESCRIPTION
**Pull request by VaishnaviShri**
The search bar on top of my courses fragment does not filter courses in MyCourses based on a parameter. It rather helps the user to search for a particular course from MyCourses.
 
Hence, replaced the "Filter my courses" hint in the edit text with "Search my courses". 
Also, replaced the filter icon with a magnifying glass icon

WhatsApp Image 2020-05-17 at 10 12 23 AM

### CODE REVIEW

**Comment by SKrPl** [comment]
@abhijeetviswa can you please update the readme regarding contribution guidelines. And add that if it's a UI related change, then the PR should have a screenshot of the same.

**Comment by abhijeetviswa** [comment]
> 
> 
> @abhijeetviswa can you please update the readme regarding contribution guidelines. And add that if it's a UI related change, then the PR should have a screenshot of the same.

Alright. Will do.

**Comment by SKrPl** [comment]
Wow, the UI of the app has changed a lot. It looks really good. cc: @harsu-ag

**Comment by abhijeetviswa** [comment]
Everything looks good. Thanks.

**Pull request merged**
