### PR TITLE
Fix Re-download option to rewrite files

### LINKED ISSUE #105: DownloadManager doesn't rewrite files
Android's DownloadManger doesn't rewrite files. However, re-downloading course files is an option in the app. When a file is re-downloaded, the filename is appended with a number. Viewing the file from within the app will result in the first (not latest) download to be opened. This is not the behaviour a user would expected. The app should rewrite previous downloads (or rename the previous download).

### PR DESCRIPTION
**Pull request by VaishnaviShri**
Re-downloading a file now rewrites the previously downloaded version of the file. Re-downloading a file earlier downloaded a new copy of the file and the filename was appended with a number. On opening the file from within the app always opened the first download, which might in some cases get corrupted.

Closes #105

### CODE REVIEW

**Comment by abhijeetviswa** [comment]
Rebased onto development and force pushed changes. 

This does not support for the `FolderModuleFragment`. Checkout `FolderModuleFragment.downloadOrOpenFile`.

**Comment by abhijeetviswa** [comment]
Also, add to `CHANGELOG.md` please.

**Comment by abhijeetviswa** [comment]
Thanks.

**Comment by abhijeetviswa** [comment]
I didn't notice this was a PR into `crux-bphc:master`. Long story short, I had to cherry-pick the commit in development and push it. Please ensure that your pr is into `crux-bphc:development` from now on out.

**Comment by VaishnaviShri** [comment]
Sorry about that. I will keep that in mind in the future.

**Pull request merged**
